-- Event Suppliers Audit Log setup
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text,
  record_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
drop policy if exists "audit_logs_admin_read" on public.audit_logs;
drop policy if exists "audit_logs_admin_insert" on public.audit_logs;
drop policy if exists "audit_logs_admin_update" on public.audit_logs;
drop policy if exists "audit_logs_admin_delete" on public.audit_logs;
create policy "audit_logs_admin_read" on public.audit_logs for select to authenticated using (public.is_admin());
create policy "audit_logs_admin_insert" on public.audit_logs for insert to authenticated with check (public.is_admin());
create policy "audit_logs_admin_update" on public.audit_logs for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "audit_logs_admin_delete" on public.audit_logs for delete to authenticated using (public.is_admin());
grant all on public.audit_logs to authenticated;
