-- Event Suppliers: flexible multi-platform supplier contacts
create table if not exists public.supplier_contacts (
  id bigint generated by default as identity primary key,
  supplier_id uuid not null references public.suppliers(id) on delete cascade,
  platform text not null check (platform in ('facebook','messenger','mobile','viber','wechat','whatsapp','telegram','email','website','custom')),
  label text,
  value text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists supplier_contacts_supplier_idx on public.supplier_contacts(supplier_id, sort_order);
alter table public.supplier_contacts enable row level security;

drop policy if exists "supplier_contacts_public_read" on public.supplier_contacts;
drop policy if exists "supplier_contacts_admin_insert" on public.supplier_contacts;
drop policy if exists "supplier_contacts_admin_update" on public.supplier_contacts;
drop policy if exists "supplier_contacts_admin_delete" on public.supplier_contacts;

create policy "supplier_contacts_public_read" on public.supplier_contacts for select to anon, authenticated using (is_active = true or public.is_admin());
create policy "supplier_contacts_admin_insert" on public.supplier_contacts for insert to authenticated with check (public.is_admin());
create policy "supplier_contacts_admin_update" on public.supplier_contacts for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "supplier_contacts_admin_delete" on public.supplier_contacts for delete to authenticated using (public.is_admin());

grant select on public.supplier_contacts to anon, authenticated;
grant insert, update, delete on public.supplier_contacts to authenticated;
grant usage, select on sequence public.supplier_contacts_id_seq to authenticated;

-- Migrate existing legacy contact columns once, without duplicating identical contacts.
insert into public.supplier_contacts (supplier_id, platform, value, sort_order)
select id, 'facebook', facebook_url, 1 from public.suppliers s
where coalesce(facebook_url,'') <> ''
and not exists (select 1 from public.supplier_contacts c where c.supplier_id=s.id and c.platform='facebook' and c.value=s.facebook_url);

insert into public.supplier_contacts (supplier_id, platform, value, sort_order)
select id, 'messenger', messenger_url, 2 from public.suppliers s
where coalesce(messenger_url,'') <> ''
and not exists (select 1 from public.supplier_contacts c where c.supplier_id=s.id and c.platform='messenger' and c.value=s.messenger_url);

insert into public.supplier_contacts (supplier_id, platform, value, sort_order)
select id, 'mobile', contact_number, 3 from public.suppliers s
where coalesce(contact_number,'') <> ''
and not exists (select 1 from public.supplier_contacts c where c.supplier_id=s.id and c.platform='mobile' and c.value=s.contact_number);

notify pgrst, 'reload schema';
